### ISSUE TITLE
fbx animation bug 

### ISSUE THREAD

**Issue by 544531645** [google-ar/sceneform-android-sdk#599] opened 2019-03-15 07:56 UTC
When my model animates, the model disappears from the screen

[shark.zip](https://github.com/google-ar/sceneform-android-sdk/files/2969950/shark.zip)

**Comment by 544531645** [comment] 2019-03-20 04:10
![image](https://user-images.githubusercontent.com/15622364/54658580-14f68580-4b09-11e9-9b8b-c2357e5cbd3b.png)
![image](https://user-images.githubusercontent.com/15622364/54658583-16c04900-4b09-11e9-8a8e-80f22aa781af.png)
The model is strange and far away

**Comment by 544531645** [comment] 2019-03-20 04:10
@tpsiaki

**Comment by fredsa** [comment] 2019-03-28 18:11
Closing as this issue is missing key information to help us reproduce it.
- Android Studio version
- Sceneform version
- Device manufacturer, model, and O/S
- ARCore APK installed version:
  On Windows, use: `adb shell pm dump com.google.ar.core | findstr /i "packages: versionName"`
  On macOS, use: `adb shell pm dump com.google.ar.core | egrep -i versionName\|packages:`
- Output of `adb shell pm path com.google.ar.core`
- Output of `adb shell getprop ro.build.fingerprint`
- Specific error message or problem encountered

**Closed by fredsa** 2019-03-28 18:11 UTC

**Comment by vortice3D** [comment] 2019-06-19 14:00
Hi everybody:

This same issue is happening to me.

I have a scene with two non-animated cubed and a series of primitives moving around then.

When I start the animation (animated FBX) one of the cubes disappear.

My info is:
- Android Studio 3.4.1
- Sceneform 1.9
- Device: Samsung Galaxy Tab S4
- ARCore APK installed version: 1.9.190422066
- adb shell pm path com.google.ar.core shows: package:/data/app/com.google.ar.core-UoGDdLIBWa56K4CEvkWrUg==/base.apk
- adb shell getprop ro.build.fingerprint shows: samsung/gts4lwifixx/gts4lwifi:9/PPR1.180610.011/T830XXU2BSD1:user/release-keys

Any help or advice with this?

**Comment by aurangzaibumer777** [comment] 2019-07-12 13:46
same issue
Android Studio 3.4.1
Build #AI-183.6156.11.34.5522156, built on May 2, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Issue: the model disappears when i try to run animation. 
Device: S9

**Comment by vortice3D** [comment] 2019-07-14 19:13
Hi there:

In my case it was due to a non-set-to-zero rotation in one of the parent-child hierarchy of the 3d model.

**Alias-Wavefront Maya** seems to let some nodes with subtle cuasi-zero orientations that drives **Sceneform** crazy in the moment it traverse all the hierarchy in order to animate the whole scene.

Solved problem!

**Comment by aurangzaibumer777** [comment] 2019-07-14 19:38
> Hi there:
> 
> In my case it was due to a non-set-to-zero rotation in one of the parent-child hierarchy of the 3d model.
> 
> **Alias-Wavefront Maya** seems to let some nodes with subtle cuasi-zero orientations that drives **Sceneform** crazy in the moment it traverse all the hierarchy in order to animate the whole scene.
> 
> Solved problem!

can you be more specific about the issue you solved earlier. 
I've had tons of fbx tried on it but nothing worked out. I'm stuck for the last 5 days and it's been a real pain.

**Comment by vortice3D** [comment] 2019-07-14 21:00
As said we're using Maya as our 3D authoring tool.

Are you using that sw too?

**Comment by aurangzaibumer777** [comment] 2019-07-14 21:40
Yes using the same software but any guide what needs to be checked first? Like a checklist that sums up things to get the animation running.

**Comment by vortice3D** [comment] 2019-07-15 07:31
Hi there, Aurangzaib:

After talking with the 3D artist, for a more detailed info, he says me that the problem comes with the existence of non-zero values in the pivots space attributes of some of the scene **transform nodes**:

![PivotsSpace](https://user-images.githubusercontent.com/1760601/61200621-5deacf00-a6e2-11e9-8ee3-ddd4eabbe5b4.jpg)

That pivot values, more specifically the ones about local-space are tweaked by the tool with each UI manipulation of the nodes.

As a solution you need to have them set to zero (as shown in the previously attached image). Please note that this must be done in a per-node basis. As an important reminder the zero setting must be done **node by node** (not shortcut here).

Best regards.

**Comment by aurangzaibumer777** [comment] 2019-08-02 15:08
> Hi there, **Aurangzaib**:
> 
> After talking with the 3D artist, for a more detailed info, he says me that the problem comes with the existence of non-zero values in the pivots space attributes of some of the scene **transform nodes**:
> 
> ![PivotsSpace](https://user-images.githubusercontent.com/1760601/61200621-5deacf00-a6e2-11e9-8ee3-ddd4eabbe5b4.jpg)
> 
> That pivot values, more specifically the ones about local-space are tweaked by the tool with each UI manipulation of the nodes.
> 
> As a solution you need to have them set to zero (as shown in the previously attached image). Please note that this must be done in a per-node basis, I mean "node by node" (not shortcut here).
> 
> Best regards.

Thanks, i got the animation working but now facing a different issue, if i open the fbx on windows 10 viewer, it shows exactly the same as it was exported from 3D software (Maya 2017) but when i rendered it on arcore - android, it gives me weird result in-terms of quality

https://drive.google.com/file/d/1T9X1ZxsjtXTxHCddBFoVUODCKdRPMD3s/view?usp=sharing

I've uploaded the video of how it is rendered on mobile. Specifically the **shoulder cloth and face**

can you please help on this? link has both the FBX model and the video that i captured on.

Thanks

**Comment by vortice3D** [comment] 2019-08-05 09:20
Hi **Aurangzaib**:

I apologize for the inconvenience. but, sadly, my **_3D Arts_** colleague is at the moment on his summer holiday until the last week of this month.

As soon as he's here again I'll let him know about your question.

Best regards.

**Comment by aurangzaibumer777** [comment] 2019-08-15 11:39
> Hi **Aurangzaib**:
> 
> I apologize for the inconvenience. but, sadly, my **_3D Arts_** colleague is at the moment on his summer holiday until the last week of this month.
> 
> As soon as he's here again I'll let him know about your question.
> 
> Best regards.

any updates now?
Thanks

**Comment by aurangzaibumer777** [comment] 2019-08-21 11:27
bump

**Comment by vortice3D** [comment] 2019-08-26 11:21
Hi there!

I don´t know if you're already solved the "quality problems" you mentioned in your post.

Anyway, what do you mean with "problems"? Are they the geometry ripples in the neck of the male model?

Best regards.

**Comment by aurangzaibumer777** [comment] 2019-08-26 11:34
haven't resolved the issue
have you checked the video? the quality of the model is the problem

**Comment by vortice3D** [comment] 2019-08-26 12:09
Yes, my colleague just opened the video and FBX file, on both Maya and Autodesk FBX Viewer, and it is shown OK as you say.

Said this, sadly it's probably a Sceneform engine problem. I regret that we cannot offer you any help with this.

Best regards.

**Comment by aurangzaibumer777** [comment] 2019-08-26 12:11
yes it is showing fine on maya and windows 3D viewer as per said earlier but on sceneform.

**Comment by vortice3D** [comment] 2019-08-26 12:24
Well, maybe you must open a new issue about this in a more general (not only Android-bound) Sceneform forum.

Sceneform issues seems to be hard to solve with the aid of the (still small) community.

Good luck with it!

**Comment by aurangzaibumer777** [comment] 2019-08-27 05:38
> Well, maybe you must open a new issue about this in a more general (not only Android-bound) Sceneform forum.
> 
> Sceneform issues seems to be hard to solve with the aid of the (still small) community.
> 
> Good luck with it!

Yeah, i already opened a new issue, been four weeks but no reply
https://github.com/google-ar/sceneform-android-sdk/issues/808

Let's hope google start taking AR more seriously soon enough
