### ISSUE TITLE
Camera blur issue while use ARCore.

### ISSUE THREAD

**Issue by mistrydarshan99** [google-ar/sceneform-android-sdk#85] opened 2018-06-07 11:54 UTC
Hello,
I have created sample app using ARCore SDK. But one issue I have found every time that ARCore Camera is a blur. I have used Samsung Galaxy S8 to test AR functionality.

**Comment by AdrianAtGoogle** [comment] 2018-06-08 20:33
Hi @mistrydarshan99, can you say more about this issue?  Do you mean the camera is not focusing correctly?  A screen capture would definitely help us understand as well, if possible.

**Comment by mistrydarshan99** [comment] 2018-06-11 10:53
Hi, @AdrianAtGoogle Camera is not focused correctly while I am using ARCore camera. I have testing ARCore functionality in Samsung Galaxy S8. Here I have attached two images of the same object using Samsung Galaxy S8.

1) ARCore Camera result :
![arcore](https://user-images.githubusercontent.com/5453894/41227738-82b3bd4e-6d93-11e8-86a5-1f6e4b471c88.jpg)

2)Samsung Galaxy S8 Camera Result
![20180611_161658](https://user-images.githubusercontent.com/5453894/41227797-b4df62fa-6d93-11e8-988a-f8f6eddc39a1.jpg)

**Comment by malik-at-work** [comment] 2018-06-11 17:38
Currently ARCore uses a fixed focus to ensure stable camera intrinsics. We may introduce autofocus or focus control in the future.

Duplicate of https://github.com/google-ar/arcore-android-sdk/issues/153

**Comment by dsternfeld7** [comment] 2018-06-25 21:51
Closing, please track this issue through [google-ar/arcore-android-sdk#153](google-ar/arcore-android-sdk#153)

**Closed by dsternfeld7** 2018-06-25 21:51 UTC
Labels: duplicate
