### ISSUE TITLE
VideoView as ViewRenderable

### ISSUE THREAD

**Issue by AKKamath** [google-ar/sceneform-android-sdk#75] opened 2018-06-06 06:27 UTC
I was trying to place a 2D video onto a 3D object using VideoViews. What happened was the VideoView just popped up like a normal view and covered the screen. Is it possible to use VideoView in ViewRenderable? If not, which views are supported?

**Comment by dsternfeld7** [comment] 2018-06-07 17:56
VideoView doesn't work because it uses a SurfaceView, which is rendered by Android differently from other views in the view hierarchy. We are looking into ways that we can support video in the future.

Closing because this is a duplicate of issue [https://github.com/google-ar/sceneform-android-sdk/issues/9](https://github.com/google-ar/sceneform-android-sdk/issues/9). Please watch for updates on this feature request in the other issue.

**Closed by dsternfeld7** 2018-06-07 17:56 UTC
Labels: duplicate, feature request
