### ISSUE TITLE
Error while converting obj to sfb

### ISSUE THREAD

**Issue by mhdtouban** [google-ar/sceneform-android-sdk#93] opened 2018-06-11 22:00 UTC
ERROR: Jsonnet Error: [1]: RUNTIME ERROR: Parameter 'roughness' doesn't have any applicable options
third_party/arcore/ar/rendercore/converter/data/mat_helpers.jsonnet:(162:5)-(177:24)	function 
third_party/arcore/ar/rendercore/converter/data/mat_helpers.jsonnet:199:23-73	object <param_opt_from_name>
third_party/arcore/ar/rendercore/converter/data/mat_helpers.jsonnet:203:23-53	object <param_init_from_name>
third_party/arcore/ar/rendercore/converter/data/mat_helpers.jsonnet:230:26-51	object 
std.jsonnet:158:56-67	thunk <array_element>
third_party/arcore/ar/rendercore/converter/data/import_meta_material.jsonnet:(11:19)-(12:44)	object 
During manifestation

Command Line: /AR-Testing/app/build/sceneform_sdk/mac/converter --no_sfb --mat build/sceneform_sdk/default_materials/obj_material.sfm -a --matc AR-Testing/app/build/sceneform_sdk/mac/matc --outdir AR-Testing/app/build/.sfa771261066923969224 sampledata/BANH VONG MIN.obj
:app:createAsset-src_47main_47assets_47BANH_32VONG_32MIN FAILED

**Comment by malik-at-work** [comment] 2018-06-13 16:28
We have confirmed this issue and have a fix for it internally.

**Comment by michaelvogt** [comment] 2018-06-26 02:22
Just tried to convert a model with plugin and sceneform version 1.3. Still showing the same exception.

**Comment by malik-at-work** [comment] 2018-06-26 16:09
@michaelvogt can you send me the obj that has this issue.

**Comment by malik-at-work** [comment] 2018-06-26 16:10
Tracking this down.  It looks like the fix didn't make the 1.3 release train, but is still in our codebase.

**Comment by tpsiaki** [comment] 2018-08-08 15:09
This was fixed in our 1.4 release of the Sceneform Gradle plugin.  Please update com.google.ar.sceneform:plugin to 1.4.0 in your project build.gradle file and these assets should import correctly.

**Closed by tpsiaki** 2018-08-08 15:09 UTC
Labels: bug
