### ISSUE TITLE
Error on Sceneform assets import

### ISSUE THREAD

**Issue by mhdtouban** [google-ar/sceneform-android-sdk#92] opened 2018-06-11 14:49 UTC
While trying to add 3d model and once I import scene form assets I get the following error

Cannot add task ':app:compileAsset-src_47main_47assets_47Heart' as a task with that name already exists.
error creating sfa

AS:3.2canary17

**Comment by mhdtouban** [comment] 2018-06-11 14:58
* What went wrong:
Execution failed for task ':app:createAsset-src_47main_47assets_47pringels'.
> Error creating sfa.

**Comment by tpsiaki** [comment] 2018-06-11 22:45
@mhdtouban - It looks like you may be trying to import something that's already been imported once. 
 Will you send a snippet of your app build.gradle file containing all of the entries that start with sceneform.asset?

**Comment by mhdtouban** [comment] 2018-06-12 10:39
That's right, but would be more grateful to replace it ? instead of such error.

**Comment by tpsiaki** [comment] 2018-06-14 14:29
@mhdtouban - could you provide more context for what you are changing that requires you to reimport rather than simply rebuild using the existing gradle rule (generated by the initial import)?

If you change any of the inputs, such as the 3d model file, textures, etc... the .sfb will be automatically rebuilt when you build your Android Studio project because it is part of your gradle build once you've imported once, so you should not need to import more than one time when you are just modifying your assets.

**Comment by mhdtouban** [comment] 2018-06-14 14:36
The error happens when I try to convert another file and not the same one.

**Comment by tpsiaki** [comment] 2018-06-14 14:40
but it looks like there's a duplicate of at lest one of the rules, correct?

The error you mentioned above indicates that the `src/main/assets/Heart` was likely imported twice.

**Closed** 2018-06-25 20:04 UTC

**Comment by Abdullahbtechit** [comment] 2018-07-11 05:31
please keep the models inside the app.

**Comment by CarlosVillagran** [comment] 2020-01-11 18:41
is it a solution?
