### ISSUE TITLE
How to specifically scale model using pinch gesture in either lengthwise of bredthwise?

### ISSUE THREAD

**Issue by ishaang10** [google-ar/sceneform-android-sdk#607] opened 2019-03-19 10:28 UTC
i have a box. i want to just scale in up or down  lengthwise rather than in every axes.
How can i tweak into 
scaleController  and pinch gesture to do this??

**Comment by fredsa** [comment] 2019-03-28 18:04
duplicate of #623

**Closed by fredsa** 2019-03-28 18:04 UTC
Labels: duplicate
