### ISSUE TITLE
Sample projects stop detecting surfaces after some time (Moto G6)

### ISSUE THREAD

**Issue by Steven0110** [google-ar/sceneform-android-sdk#294] opened 2018-08-29 22:54 UTC
Hi, I've just bought a Moto G6. In the overview is said that this phone is compatible with ARCore.
I've installed the four sample projects, and all of them work fine. But after launching and closing them several times, suddenly the feature points are not shown, and surfaces are not detected anymore. The camera is working but it behaves as if there wasn't any planes in the environment.
Rebooting the phone makes the apps work again, but then after a few tests, surface detection does not work again.
I don't know if that's a problem with the phone (I'm testing on a new one) or it's a problem with the SDK.

**Comment by abramyan** [comment] 2018-09-01 00:30
Thank you for bringing this to our attention. Our team will look into it.

**Comment by abramyan** [comment] 2018-10-08 20:55
@Steven0110 We've tried various ways to test this but we're unable to reproduce your issue with ARCore 1.4. Are you still experiencing this issue with 1.5? What are the names of the sample projects you're testing with? Can you give us more device info?

**Comment by abramyan** [comment] 2018-10-09 22:52
Make sure to remove the `abiFilters 'arm64-v8a', 'x86'` in the build.gradle files.

**Comment by abramyan** [comment] 2018-10-23 00:01
We've confirmed that Moto G6 has a timestamp issue, which explains why you are able to initially detect planes, but are unable to after a period of time. We will have a fix in an upcoming release.

**Comment by Steven0110** [comment] 2018-10-25 19:34
Do you know how much time does it take to work again? I'm developing a project with ARCore, and knowing that info would be so helpful for our tests.

Thanks a lot in advance.

**Comment by fredsa** [comment] 2019-03-28 17:18
Fixed by updates to ARCore.

**Closed by fredsa** 2019-03-28 17:18 UTC
Labels: bug, fixed in upcoming release
