### ISSUE TITLE
Sceneform Objects when resolved from Cloud Anchors are not placed on the surface.

### ISSUE THREAD

**Issue by rohitagarwal3011** [google-ar/sceneform-android-sdk#170] opened 2018-07-07 06:39 UTC
I am hosting multiple nodes using Cloud Anchors and I am able to resolve them too. But the problem is that when we resolve the nodes they are not perfectly placed on the surface. They keep floating in the air and the position of the nodes are slightly shifted up to 2-3 meters.

**Comment by dsternfeld7** [comment] 2018-07-09 18:59
Are you setting the position of the nodes by setting the world position, or the local position relative to the cloud anchor?

**Comment by rohitagarwal3011** [comment] 2018-07-09 19:00
Local position relative to cloud anchor.

**Comment by claywilkinson** [comment] 2018-07-13 22:44
Can you share a screenshot of the problem?

To confirm what you are doing:

On the hosting side, you are placing an anchor (is it on a plane or an oriented point or image)?
Capturing the local positions of the children of the anchorNode.

Then on the resolving side you resolve the anchor successfully, retrieve the local positions from the hosting side, and position the child nodes of the anchorNode based on the resolved anchor by calling setLocalPosition().

**Comment by rohitagarwal3011** [comment] 2018-07-14 08:37
@claywilkinson Yes this is exactly what i am doing.

**Comment by rohitagarwal3011** [comment] 2018-07-14 08:40
I will try to send a proper screenshot in which the problem can be understood easily.

**Comment by dsternfeld7** [comment] 2018-08-01 22:59
Closing due to inactivity.

**Comment by luislukas** [comment] 2018-09-26 20:18
@dsternfeld7 I would like to follow up this issue since I'm experiencing the same. These are the steps I follow:
**To save in Firebase**
`
val frame = mArFragment.arSceneView.arFrame
val anchor = hitResult.createAnchor()

val imageNode = Node()
imageNode.renderable = myRenderable

val anchorNode = AnchorNode(anchor)
imageNode.setParent(anchorNode)

fragment.arSceneView.scene.addChild(anchorNode)

val cloudAnchor = mSession?.hostCloudAnchor(anchor)
mCloudAnchor?.let {
     //if cloudAnchor.cloudAnchorState is Anchor.CloudAnchorState.SUCCESS
    //Then store cloudId AND the local position
     storeInTheCloud(cloudAnchor.cloudAnchorId, anchorNode.localPosition)
}
` 

**Retrieving  from Firebase**
`
val vector3 = // it's stored in Firebase with the given cloudId
val anchorFromCloud = mSession?.resolveCloudAnchor(key)
val imageNode = Node()
imageNode.renderable = myCustomRenderable

val anchorNode = AnchorNode(anchorFromCloud)
imageNode.setParent(anchorNode)
anchorNode.localPosition = vector3

fragment.arSceneView.scene.addChild(anchorNode)
`
If I resolve from the cloud the anchor just holding the phone at the same position as I stored it, it pretty much looks like the original, just a slight hovering over the ground.
If I go somewhere else in the room, the resolved object it's either floating in the room or looking really small and in a different place other than the original.
In either case I apply any scaling or re-sizing etc.

Let me know if you need more info.

**Comment by luislukas** [comment] 2018-09-26 20:32
Attached here are the images, original and resolved (from another point in the room).
![original](https://user-images.githubusercontent.com/5175738/46107585-a547b380-c1d3-11e8-88ee-9a2d7e19ad1c.jpg)
![resolved](https://user-images.githubusercontent.com/5175738/46107583-a547b380-c1d3-11e8-9c52-a6043f7be2da.jpg)

**Comment by malik-at-work** [comment] 2018-10-12 17:36
Reopening this to look at it.

**Comment by abramyan** [comment] 2018-10-19 17:34
> In either case I apply any scaling or re-sizing etc.

@luislukas just to clarify, you **do** or **don't** apply any scaling or resizing?

**Comment by luislukas** [comment] 2018-10-20 20:47
Hi @abramyan I **do not** apply any scaling or resizing. I just resolve the cloud anchor and add the Renderable there.

**Comment by luislukas** [comment] 2018-11-02 12:10
Just reading the ArCore documentation on cloud anchors, seems that the following recommendations might be the cause of the behaviour I experience:

> Hosting
> Before hosting an anchor:
> 
> Try to look at the anchor from different angles.
> Move around the anchor for at least a few seconds.
> **Make sure you are not too far away from the anchor**.
> Resolving
> When resolving an anchor:
> 
> Make sure you are close to where the anchor was hosted.
> **If you are too far away from a cloud anchor’s position, it might resolve incorrectly**.
> A Cloud Anchor might resolve incorrectly if your device camera is pointed at a space that is different from but visually identical to where the Cloud Anchors were hosted.

**Comment by abramyan** [comment] 2018-11-12 23:22
@luislukas Did the recommendation from the documentation solve the issue?

**Comment by luislukas** [comment] 2018-11-13 11:12
@abramyan following the recommendations does solve the issue, ie. if you create and store a cloud anchor and resolve it in the same position it is displayed well. However, If you move, let's say, 3 or 4 metres away from where you created the anchor including a change in the camera position, it keeps behaving wrongly. 
My use case involves creating and storing cloud anchors within a room and then resolving them from people entering the room for example, without knowing exactly where the anchors were created. I would expect that people coming into the room would see the resolved objects in the same position at least, so that they could walk in and explore the area, come closer to the object and see it.

**Comment by praveenbbhati** [comment] 2019-08-07 14:15
Hi everyone, any update in 2019?

**Comment by malik-at-work** [comment] 2019-11-21 00:45
The ArCore team has been paying attention to this and has been incrementally improving it.  Current versions of ArCore resolve cloud anchors much closer now.   This may continue to improve but we are not tracking it as a bug.  Closing this for now since they have marked it resolved internally.

**Closed by malik-at-work** 2019-11-21 00:45 UTC
