### ISSUE TITLE
Convert mutliple .obj to .sfa and .sfb

### ISSUE THREAD

**Issue by ManuelTS** [google-ar/sceneform-android-sdk#217] opened 2018-07-27 07:11 UTC
With the import wizard in Android Studio which imports one Sceneform asset, allow to select a directory full of .obj files and to convert all of them as a batch to .sfa and .sfb files.

I have circa 3.000 .obj files, how can I convert them automatically to .sfa and .sfb files?

**Comment by ManuelTS** [comment] 2018-07-30 13:07
Thanks for the link and your hint. I did the same and it works perfectly. But where did you find the converter program as well as matc? The SDK downloads of ARCore lack those two:
https://developers.google.com/ar/develop/downloads

**Comment by necrostylery** [comment] 2018-07-30 15:42
I extracted them from the sceneform gradle plugin jar file.

**Comment by ManuelTS** [comment] 2018-07-31 07:50
Great deed. But you don't get in Android Studio the message "File was loaded in the wrong encoding..." no matter if you reload it with UTF-8, -16, ISO-8859-1, or US-ASCII?

**Comment by necrostylery** [comment] 2018-07-31 15:59
Hi @ManuelTS, 
about this wrong encoding, I've never seen something similar with my assets. This error is reproduced with sceneform gradle plugin? 

Maybe you should open a different issue for this problem.

**Comment by ManuelTS** [comment] 2018-08-01 08:10
Done in issue #226.

**Comment by ManuelTS** [comment] 2018-08-01 21:49
A manual import works now, but an self made automatic one via shell script not. The Sceneform plugin got updated to 1.4.0
https://plugins.jetbrains.com/plugin/10698-google-sceneform-tools-beta-
I am unable to extract the converter and matc from the .jar files. Not a single .jar in there is close the size of 25 MB, how and from which .jar did you do the extraction? Another approach is you extract them and update your repo, maybe then I can make it work. I was so bold to make an issue in your repo:
https://github.com/necrostylery/google-ar-asset-converter/issues/6

**Comment by necrostylery** [comment] 2018-08-03 22:41
Hi @ManuelTS ! I updated the repo binaries, please try again!

**Comment by ManuelTS** [comment] 2018-08-10 10:27
Hi @necrostylery, sorry I got caught up in [implementing other features of my app](https://github.com/google-ar/sceneform-android-sdk/issues/250) and now I'm back to generating multiple .sfb files, the error persists, I made a script to process all the ~3000 files. Since your update of binaries I redid the first two files of my database by hand, here the single commands:
```
cd appRootDir/base/sampledata

wget https://github.com/necrostylery/google-ar-asset-converter/raw/master/sceneform_sdk/linux/converter
wget https://github.com/necrostylery/google-ar-asset-converter/raw/master/sceneform_sdk/linux/matc
wget https://raw.githubusercontent.com/necrostylery/google-ar-asset-converter/master/sceneform_sdk/default_materials/obj_material.sfm

sudo chmod 777 converter
sudo chmod 777 matc
sudo chmod 777 obj_material.sfm

cp xxxxxx/database/*.obj ./
<fj1252.obj, fj1253.obj, converter, matc, and obj_material.sfm are now in appRootDir/base/sampledata>

./converter -a -d --mat obj_material.sfm --outdir models/ fj1252.obj
./converter -a -d --mat obj_material.sfm --outdir models/ fj1253.obj
<fj1252.sfb and fj1253.sfb along with their .sfa files are now in appRootDir/base/sampledata/models>
```
But both generated .sfb files give me [the aforementioned error](https://github.com/google-ar/sceneform-android-sdk/issues/217#issuecomment-409128972).

I'm startled, what am I doing wrong?

**Comment by necrostylery** [comment] 2018-08-13 13:16
Hi @ManuelTS,
could you send me some of the assets? I will try to identify your problem.

**Comment by ManuelTS** [comment] 2018-08-14 08:04
Thank you for your support @necrostylery ! Of course I can:
[Frist2Files.zip](https://github.com/google-ar/sceneform-android-sdk/files/2286005/Frist2Files.zip)

**Comment by necrostylery** [comment] 2018-08-14 12:39
Hi @ManuelTS, I tried run this command:

```
cd ~/
mkdir github
cd github
git clone https://github.com/necrostylery/google-ar-asset-converter.git
cd google-ar-asset-converter
cp ~/Downloads/Frist2Files/FJ1252.obj ./input
cp ~/Downloads/Frist2Files/FJ1253.obj ./input
./sceneform_sdk/mac/converter -a -d --mat ./sceneform_sdk/default_materials/obj_material.sfm --outdir ./output/ ./input/FJ1252.obj
./sceneform_sdk/mac/converter -a -d --mat ./sceneform_sdk/default_materials/obj_material.sfm --outdir ./output/ ./input/FJ1253.obj
```

That's the output messages:

```
Warning: Imported asset was very large (69.5 x 53.9 x 18.4 m)
         Setting scale to: 0.0544069 to compensate
Info: Generated SFA from ./input/FJ1252.obj
Info: Wrote SFA (json) to ./output/FJ1252.sfa (957 bytes)
Info: Wrote SFB to ./output/FJ1252.sfb (121416 bytes)

Warning: Imported asset was very large (75.3 x 53.5 x 36.0 m)
         Setting scale to: 0.0277778 to compensate
Info: Generated SFA from ./input/FJ1253.obj
Info: Wrote SFA (json) to ./output/FJ1253.sfa (957 bytes)
Info: Wrote SFB to ./output/FJ1253.sfb (119432 bytes)
```
and the output folder:
```
total 1160
drwxr-xr-x  8 guilherme  staff     272 Aug 14 09:33 .
drwxr-xr-x  7 guilherme  staff     238 Aug  3 10:45 ..
-rw-r--r--  1 guilherme  staff     957 Aug 14 09:33 FJ1252.sfa
-rw-r--r--  1 guilherme  staff  121416 Aug 14 09:33 FJ1252.sfb
-rw-r--r--  1 guilherme  staff     957 Aug 14 09:33 FJ1253.sfa
-rw-r--r--  1 guilherme  staff  119432 Aug 14 09:33 FJ1253.sfb
```
It worked normally for me, maybe is some problem with your OS system?? Have you tried with another computer?

Sorry if I couldn't help more.

**Comment by ManuelTS** [comment] 2018-08-14 16:48
I did the same with he same result, only difference is I used the converters from linux and from windows with wine. All .sfb files show in Android Studio "File was loaded in the wrong encoding...". :( Can you upload your generated files so I can open them with my Android Studio?

**Comment by ManuelTS** [comment] 2018-08-16 14:12
@necrostylery propably a bug, no I have no since I cannot export circa 3000 files. As far as I know no special characters are in there. However, I will do exactly this for the two files attached here and I will report back.

My full explanation and conclusion for the Sceneform developer team:

I use objects from [download # 9 from the BodyParts3D database](https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html). When I create a single sfa and .sfb out of an .obj file with the android studio importer wizard the file works, see #226. But creating [one or multiple files via command line](https://github.com/google-ar/sceneform-android-sdk/issues/217#issuecomment-412043632) lets Android Studio, or rather its Sceneform plugin, say ["File was loaded in the wrong encoding..."](https://github.com/google-ar/sceneform-android-sdk/issues/217#issuecomment-409128972). This applies to files created on Ubuntu 18.04, Windows 10, and Mac. Here the same single generated .sfa and .sfb files from .obj files from the [Body Parts 3D database](https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html):

- [Ubuntu.zip](https://github.com/google-ar/sceneform-android-sdk/files/2293923/Ubuntu.zip)
- [Windows10.zip](https://github.com/google-ar/sceneform-android-sdk/files/2293919/Windows10.zip)
- [Mac.zip](https://github.com/google-ar/sceneform-android-sdk/files/2293920/Mac.zip)
And the object files too
- [Objs.zip](https://github.com/google-ar/sceneform-android-sdk/files/2293955/Objs.zip)
I think since it is a scientific DB the .obj files should be okay, but nobody can really know for sure. After a reexport via a designer software and regeneration of .sfa and .sfb files I will report back.

**Comment by ManuelTS** [comment] 2018-08-18 07:38
This story has gone a long way and to be honest I don't care anymore, it takes too long and too much time, look at all the workarounds and tries before, I'm frustrated I cannot view the models in Android Studio. I know that the models render nonetheless in ARCore.

Why the sceneform guys did not included a simple multiple file-to-.sfa-.sfb conversion is beyond me, [new File().listFiles()](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#listFiles()) should no be too hard to use, especially if you are a developer from Google.

@necrostylery, using a graphical design program for regernating the .obj files results in the following:

The two files imported into blender and exported create also FJxxxx.mtl files. Trying use the materials in the conversion results in
```
Info: Generated SFA from ./Databases/BodyParts3D/isa_BP3D_4/FJ1252_blender.obj
ERROR: Jsonnet Error: [1]: STATIC ERROR: FJ1252_blender.mtl:1:107: Unexpected: ";" while parsing terminal
```
Using the original, standard material works, here the generated files with blender. Error is the same as before:
[Blender.zip](https://github.com/google-ar/sceneform-android-sdk/files/2299234/Blender.zip)

**Comment by malik-at-work** [comment] 2018-10-10 16:13
Closing this as will not fix for now.

**Closed by malik-at-work** 2018-10-10 16:13 UTC
Labels: feature request

**Comment by ManuelTS** [comment] 2019-03-23 07:10
A issue as feature request which is closed? Shouldn't you have written "will never fix"?

**Comment by marcspraragen** [comment] 2019-07-15 18:49
Hi-- I am trying to get the sfb/sfa coverter running as a batch/command line for fbx files.
Here is my problem. The Android Studio wizard does this import perfectly. My manual try with the command line, not so much:

**Comment by ManuelTS** [comment] 2019-07-17 06:37
In this topic on [comment](https://github.com/google-ar/sceneform-android-sdk/issues/217#issuecomment-412857352) you have a bash script to give you an idea to convert multiple files. Also check out the dedicated repo [google-ar-asset-converter](https://github.com/gdamoreira/google-ar-asset-converter) of @gdamoreira. There you see how you get a short description explaining the single command line arguments of the converter.

**Comment by zabdielcead** [comment] 2019-09-11 01:20
I have a solution
update android studio  to the last version 3.5

download plugin Google sceneform tools (beta) v.11.1

update dependencies
   implementation 'com.google.ar:core:1.11.0'
    implementation 'com.google.ar.sceneform.ux:sceneform-ux:1.11.0'
    implementation 'com.google.ar.sceneform:core:1.11.0'

and again create the step import scneform from assets


actually that works for me!!!!!!! :)

**Comment by manojghorela69** [comment] 2019-10-03 12:22
I am downloading obj and mtl file using url in my Android app. Can anyone help how can I use sceneform plugin to convert them to sfb. @gdamoreira I have seen your converter but it is specifically for Windows and Linux. How can I write a script for my Android App?

**Comment by bobekos** [comment] 2019-10-03 15:26
You canno't. Actually you can do only two things. First one is to convert you models into sfb and download them or the second one you can download your models as gltf files and then you can convert them at runtime in your app.
